# Site Identity
title: Aemi Theme Website
tagline: 
logo: /assets/images/logo/favicon.svg
description: >-
  Lorem ipsum dolor sit amet consectatur
description_tagline: 

# Owner Identity
author: "Guillaume"
email: public@gcqd.fr
colophon: 

# Technical Details
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com 

# Build Settings & Plugins
theme: aemi
plugins:
  - jekyll-feed
  - aemi-seo-tag
  - jekyll-sitemap

exclude:
  - fonts.txt
  - /*.gem
  - /*.gemspec
  - README.md
  - LICENSE.txt
  - scripts/*

# Defaults Configuration
#   - Sitemap
defaults:
  -
    scope:
      path:   "assets/**/*"
    values:
      sitemap: false
  -
    scope:
      path:   "assets/*"
    values:
      sitemap: false
